CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  description VARCHAR(120) NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  category VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
